# Generated by Django 5.2.5 on 2025-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
