name: workflow.yml

on: push

env:
  PYTHON_VERSION: '3.13'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python and Poetry environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run tests
        run: |
          cp .github/.env.ci .env
          coverage run manage.py test --shuffle
          coverage report

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python and Poetry environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run lints
        run: |
          ruff check .
          ruff format --check .

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_APP }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_APP }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
